const LOGIN = {
	ERROR: {
		LENGTH: 1,
		USER_PASSWORD_INVALID: 2,
		USER_BANNED: 3,
		INTERNAL_ERROR: 4
	}
};

const REGISTER = {
	ERROR: {
		INVALID_INPUT: 1,
		USER_ALREADY_EXISTS: 2,
		EMAIL_ALREADY_IN_USE: 3
	}
};


const USERNAME_MIN_LENGTH = 3;
const USERNAME_MAX_LENGTH = 20;

const PASSWORD_MIN_LENGTH = 6;

const GAME_AUTH_TOKEN_LENGTH = 150;
const USER_CSRF_TOKEN_LENGTH = 30;

module.exports = { 
	LOGIN, 
	REGISTER, 
	USERNAME_MIN_LENGTH, 
	USERNAME_MAX_LENGTH, 
	PASSWORD_MIN_LENGTH,
	GAME_AUTH_TOKEN_LENGTH,
	USER_CSRF_TOKEN_LENGTH
};