const CHANNELS = {
    GLOBAL: () => "g",
    USERS: id => `u${id}`,
    LEVEL: id => `l${id}`
};

const EVENTS = {
    "START_GAMECLIENT": "99",
    "PING": "0",
    "USE_ITEM": "10",
    "BUY_ITEM": "11",
    "GET_MONSTER_BOX": "12",
    "SEARCH_WILD": "20",
    "ACCEPT_REJECT_WILD_BATTLE": "22",
    "CHOOSE_BATTLE_ACTION": "30",
    "TRADE_FAINTED_MONSTER_PVP": "31",
    "CLAIM_PVP_TIMER": "39",
    "EXEC_FLAG": "40",
    "CHANGE_LEVEL": "50",
    "CHANGE_SKIN": "51",
    "REQUEST_SELF_PROFILE_DATA": "52",
    "REQUEST_PROFILE_DATA": "53",
    "CHANGE_BOX_TO_PARTY": "62",
    "CHANGE_BOX_TO_EMPTY_PARTY": "63",
    "CHANGE_PARTY_TO_EMPTY_BOX": "64",
    "CHANGE_PARTY_POSITION": "65",
    "CHANGE_BOX_POSITION": "67",
    "GET_MONSTERS_ITEMS": "68",
    "GET_PLAYER_DATA": "69",
    "GET_QUESTS_LIST": "70",
    "GET_SPECIFIC_QUEST_DATA": "71",
    "GET_SPECIFIC_MONSTER_DATA": "72",
    "REQUEST_QUEST": "74",
    "REQUEST_START_QUEST": "75",
    "GET_NOTIFICATION_LIST": "80",
    "GET_MOVE_NOTIFICATION": "81",
    "GET_EVOLVE_NOTIFICATION": "82",
    "GET_MESSAGE_NOTIFICATION": "83",
    "REQUEST_LEARN_MOVE_NOTIFY_ACTION": "84",
    "REQUEST_EVOLVE_NOTIFY_ACTION": "85",
    "GET_MARKETPLACE_NOTIFICATION": "86",
    "REQUEST_DONT_LEARN_MOVE_NOTIFY_ACTION": "87",
    "SET_NOTIFICATION_SEEN": "88",
    "DISCONNECT": "disconnect"
};

module.exports = { CHANNELS, EVENTS };